### ISSUE TITLE
Network fails to simulate

### ISSUE THREAD

**Issue by bramvdh91** [ibpsa/project1#20]
At the beginning of the mid-season where heating becomes less important, temperatures in the network start dropping (see screenshot). At some point, this pushes the return temperature from one of the consumers below the freezing temperature, leading to an error in the simulation. 

![ibpsadestest_sup](https://user-images.githubusercontent.com/10756543/43526184-da903c4e-95a3-11e8-8388-b0af6581d11c.png)

Several phenomena are present here:
* Temperatures in the supply line start dropping because of (too) low mass flow rate under low heat demand
* Assumption that substation can achieve a fixed deltaT irrespective of the supply temperature is nonsense when actual supply temperature starts dropping and return temperature should not drop under the temperature to which heat is delivered.

This issue is made to open up the discussion on how to fix this bug.

**Comment by bramvdh91** [comment]
Another interesting details in the simulation result:
* The supply temperature received by the substations (see upper subplot) exceeds the actual network supply temperature at times. This could have something to do with the parameter ``addPowerToMedium``, as mentioned by @FelixBue 

If you want to check the simulation results more closely, please check out branch ``issue20_simulationFails``. The model ``IBPSAdestest.Network.SupplyNetwork_numerical`` includes two scripts (see Commands... > Simulate and plot/Plot only). If you simulate the model for a year, you can use the script ``Plot only`` to show the graphs from the screenshot above. Simulate and plot will not work yet, since the script will stop before the plotting commands are reached.

**Comment by MichaMans** [comment]
@bramvdh91 That is definitely an interesting result. We had a lot of problems with running out of the media boundaries, too. Of course, as you said, fixed delta T might not be the best solution here. As well as it might be an influence of the heat transfer to the ground. This could be too high at the moment. Maybe we can check if some kind of ground capacity model helps. I hope i can give some more input in the near future :smiley:

**Comment by bramvdh91** [comment]
Problem currently solved by increasing minimum mass flow rate (bypass), so closing this issue.
