### ISSUE TITLE
Add simple consumer model for destest

### ISSUE THREAD

**Issue by bramvdh91** [ibpsa/project1#8]
For WP3 Application and Dissemination, Network modelling subgroup

Add simple consumer model with idealized mass flow control, fixed temperature drop, zero pressure drop and ideal heat exchange.

**Comment by bramvdh91** [comment]
Opening branch ``issue8_simpleconsumer``

**Comment by bramvdh91** [comment]
Consumer model added and data connected to the right consumers.

**Comment by annvdm** [comment]
Solved in #11
