### ISSUE TITLE
Add data handling scripts for destest

### ISSUE THREAD

**Issue by annvdm** [ibpsa/project1#9]
For WP3 Application and Dissemination, Network modelling subgroup

Add scripts to convert csv files to txt files. Will be used to load building heat use profiles into the network model.

**Comment by annvdm** [comment]
Opening branch `issue9_networkdatahandling`

**Comment by bramvdh91** [comment]
Closed by #10

**Comment by bramvdh91** [comment]
Small bug found: the size of the data file for the columns should include the time axis. Script needs to be adapted to this.

**Comment by bramvdh91** [comment]
Closed by #12
